"use client"

import { useState } from "react"
import { ProductList } from "@/components/products/product-list"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@vehiverze/ui/dialog"
import { Card, CardContent, CardHeader, CardTitle } from "@vehiverze/ui/card"
import { Button } from "@vehiverze/ui/button"
import { Badge } from "@vehiverze/ui/badge"
import { Input } from "@vehiverze/ui/input"
import { Label } from "@vehiverze/ui/label"
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@vehiverze/ui/accordion"
import { RadioGroup, RadioGroupItem } from "@vehiverze/ui/radio-group"
import { Progress } from "@vehiverze/ui/progress"
import type { VehicleProduct } from "@/lib/mock-data/vehicle-types"
import { ProductForm } from "@/components/products/product-form"
import { conditionColors } from "@/lib/mock-data/vehicle-types"
import { vehiclesDb } from "@/lib/mock-data/vehicle-store"
import type { VehicleCondition } from "@/lib/mock-data/inspection-questions"
import { Save, Calculator } from "lucide-react"

// Complete 300-point inspection questions for each vehicle type
const inspectionQuestions = {
  "2 Wheeler": {
    "Engine & Performance": [
      "Engine oil level & quality",
      "Spark plug condition",
      "Air filter cleanliness",
      "Fuel system check",
      "Carburetor/FI system",
      "Exhaust system",
      "Engine mounting",
      "Cooling system",
      "Ignition timing",
      "Compression test",
      "Valve clearance",
      "Cam chain tension",
      "Oil pump function",
      "Fuel pump operation",
      "Throttle response",
      "Idle stability",
      "Engine noise check",
      "Vibration analysis",
      "Fuel consumption",
      "Emission levels",
      "Engine temperature",
      "Oil pressure",
      "Fuel line condition",
      "Intake manifold",
      "Exhaust manifold",
      "Cylinder head",
      "Piston condition",
      "Connecting rod",
      "Crankshaft",
      "Camshaft",
      "Timing chain",
      "Oil filter",
      "Fuel filter",
      "Air intake",
      "Exhaust pipe",
      "Muffler condition",
      "Engine bay cleanliness",
      "Wiring harness",
      "Sensors check",
      "ECU diagnostics",
      "Fuel injector",
      "Throttle body",
      "Engine mount rubber",
      "Oil seal condition",
      "Gasket integrity",
      "Bearing condition",
      "Valve guide wear",
      "Cylinder bore",
      "Ring condition",
      "Oil consumption",
      "Coolant level",
      "Radiator condition",
      "Fan operation",
      "Thermostat",
      "Water pump",
      "Coolant hoses",
      "Temperature sensor",
      "Oil cooler",
      "Breather system",
      "PCV valve",
    ],
    "Transmission & Drive": [
      "Clutch operation",
      "Gear shifting",
      "Chain condition",
      "Sprocket wear",
      "Chain tension",
      "Clutch cable",
      "Gear lever",
      "Shift drum",
      "Gear forks",
      "Transmission oil",
      "Final drive",
      "Chain lubrication",
      "Clutch plates",
      "Pressure plate",
      "Clutch springs",
      "Release bearing",
      "Gear teeth",
      "Synchronizers",
      "Shift mechanism",
      "Kickstart",
      "Electric start",
      "Starter motor",
      "Starter relay",
      "Neutral switch",
      "Clutch switch",
      "Side stand switch",
      "Drive chain slack",
      "Chain guard",
      "Rear sprocket",
      "Front sprocket",
      "Chain master link",
      "Swing arm bearings",
      "Swing arm bushes",
      "Drive shaft (if applicable)",
      "Universal joints",
      "CV joints",
      "Differential",
      "Axle condition",
      "Wheel bearings",
      "Hub condition",
    ],
    "Suspension & Steering": [
      "Front fork condition",
      "Rear shock absorber",
      "Fork oil level",
      "Shock oil condition",
      "Spring condition",
      "Fork seals",
      "Shock seals",
      "Steering head bearings",
      "Handle bar alignment",
      "Fork alignment",
      "Suspension travel",
      "Damping function",
      "Rebound adjustment",
      "Compression adjustment",
      "Preload setting",
      "Fork tubes",
      "Shock body",
      "Mounting points",
      "Bushings",
      "Ball joints",
      "Steering lock",
      "Handle bar grips",
      "Control cables",
      "Brake lever",
      "Clutch lever",
      "Throttle grip",
      "Kill switch",
      "Horn button",
      "Indicator switch",
      "Headlight switch",
      "High beam switch",
      "Turn signal",
      "Hazard switch",
      "Mirror adjustment",
      "Mirror condition",
      "Windscreen",
      "Fairing condition",
      "Body panels",
      "Seat condition",
      "Grab rail",
      "Foot pegs",
      "Foot rest",
      "Side stand",
      "Center stand",
      "Stand springs",
      "Stand bolts",
      "Frame condition",
      "Swing arm",
      "Rear suspension linkage",
      "Monoshock",
    ],
    "Braking System": [
      "Front brake pads",
      "Rear brake pads",
      "Brake disc condition",
      "Brake fluid level",
      "Brake lines",
      "Master cylinder",
      "Brake caliper",
      "Brake lever feel",
      "Brake pedal feel",
      "ABS function",
      "Brake hose condition",
      "Brake fluid quality",
      "Brake bleeding",
      "Disc thickness",
      "Disc runout",
      "Caliper piston",
      "Brake seals",
      "Brake reservoir",
      "Brake warning light",
      "ABS sensor",
      "ABS ring",
      "Brake pump",
      "ABS module",
      "Brake assist",
      "EBD function",
      "Brake balance",
      "Front brake lever",
      "Rear brake pedal",
      "Brake cable",
      "Drum brake shoes",
      "Brake drum",
      "Wheel cylinder",
      "Brake adjuster",
      "Brake springs",
      "Brake cam",
      "Brake panel",
      "Brake anchor",
      "Brake lining",
      "Brake dust",
      "Brake noise",
    ],
    "Electrical System": [
      "Battery condition",
      "Charging system",
      "Alternator output",
      "Headlight function",
      "Tail light",
      "Brake light",
      "Turn signals",
      "Horn operation",
      "Ignition system",
      "Spark plug wires",
      "Ignition coil",
      "CDI unit",
      "Voltage regulator",
      "Fuse box",
      "Main fuse",
      "Wiring harness",
      "Ground connections",
      "Switch functions",
      "Instrument cluster",
      "Speedometer",
      "Odometer",
      "Fuel gauge",
      "Temperature gauge",
      "Warning lights",
      "Indicator lights",
      "Neutral light",
      "High beam indicator",
      "Turn signal indicator",
      "Oil pressure light",
      "Battery light",
      "Engine light",
      "ABS light",
      "Immobilizer",
      "Alarm system",
      "Central locking",
      "Remote key",
      "Key fob battery",
      "Ignition switch",
      "Kill switch",
      "Side stand switch",
      "Clutch switch",
      "Brake switch",
      "Neutral switch",
      "Gear position sensor",
      "Speed sensor",
      "Throttle position sensor",
      "MAP sensor",
      "IAT sensor",
      "ECT sensor",
      "O2 sensor",
      "Knock sensor",
      "Cam position sensor",
      "Crank position sensor",
      "Fuel level sensor",
      "Oil pressure sensor",
      "Side stand sensor",
      "Tip over sensor",
      "USB charging port",
      "12V socket",
      "LED lights",
    ],
    "Body & Accessories": [
      "Fuel tank condition",
      "Fuel cap",
      "Seat condition",
      "Seat lock",
      "Under seat storage",
      "Tool kit",
      "Spare parts",
      "Owner manual",
      "Service book",
      "Registration papers",
      "Insurance papers",
      "Pollution certificate",
      "Body panels",
      "Fairing condition",
      "Paint condition",
      "Scratches",
      "Dents",
      "Rust spots",
      "Chrome condition",
      "Plastic parts",
      "Rubber parts",
      "Gaskets",
      "Seals",
      "Weather stripping",
      "Mirrors",
      "Mirror adjustment",
      "Windscreen",
      "Wind deflector",
      "Hand guards",
      "Leg guards",
      "Engine guard",
      "Crash bars",
      "Frame sliders",
      "Tank pad",
      "Seat cover",
      "Grab rail",
      "Luggage rack",
      "Top box",
      "Side boxes",
      "Tank bag",
      "Tail bag",
      "Mobile holder",
      "GPS mount",
      "Action camera mount",
      "Helmet lock",
      "Disc lock",
      "Chain lock",
      "Cover",
      "Stand",
      "Paddock stand",
    ],
  },
  "3 Wheeler": {
    "Engine & Performance": [
      "Engine oil level",
      "Coolant system",
      "Air filter",
      "Fuel system",
      "Injection system",
      "Exhaust system",
      "Engine mounting",
      "Cooling fan",
      "Radiator condition",
      "Thermostat",
      "Water pump",
      "Coolant hoses",
      "Timing belt",
      "Timing chain",
      "Valve clearance",
      "Compression test",
      "Oil pressure",
      "Fuel pressure",
      "Throttle response",
      "Idle quality",
      "Engine noise",
      "Vibration check",
      "Emission test",
      "Turbo system",
      "Intercooler",
      "Boost pressure",
      "Wastegate",
      "Blow-off valve",
      "Intake manifold",
      "Exhaust manifold",
      "EGR valve",
      "PCV system",
      "Crankcase ventilation",
      "Oil separator",
      "Fuel rail",
      "Fuel injectors",
      "Throttle body",
      "MAP sensor",
      "MAF sensor",
      "IAT sensor",
      "ECT sensor",
      "TPS sensor",
      "O2 sensor",
      "Knock sensor",
      "Cam sensor",
      "Crank sensor",
      "ECU diagnostics",
      "Wiring harness",
      "Ground points",
      "Ignition coils",
      "Spark plugs",
      "Ignition timing",
      "Fuel pump",
      "Fuel filter",
      "Air intake",
      "Exhaust pipe",
      "Catalytic converter",
      "Muffler",
      "DPF system",
      "AdBlue system",
      "SCR system",
      "Engine bay",
      "Oil leaks",
      "Coolant leaks",
      "Fuel leaks",
      "Vacuum leaks",
      "Boost leaks",
      "Belt condition",
      "Pulley alignment",
      "Tensioner",
    ],
    "Transmission & Drive": [
      "Clutch operation",
      "Gear shifting",
      "Transmission oil",
      "Differential oil",
      "Drive shaft",
      "CV joints",
      "Universal joints",
      "Clutch pedal",
      "Gear lever",
      "Shift cables",
      "Clutch cable",
      "Flywheel condition",
      "Pressure plate",
      "Clutch disc",
      "Release bearing",
      "Pilot bearing",
      "Transmission case",
      "Gear teeth",
      "Synchronizers",
      "Shift forks",
      "Shift rails",
      "Detent balls",
      "Springs",
      "Seals",
      "Gaskets",
      "Input shaft",
      "Output shaft",
      "Layshaft",
      "Reverse gear",
      "Final drive",
      "Ring gear",
      "Pinion gear",
      "Differential case",
      "Side gears",
      "Spider gears",
      "Axle shafts",
      "Wheel bearings",
      "Hub assembly",
      "Brake drums",
      "Brake shoes",
      "Wheel cylinders",
      "Brake lines",
      "Master cylinder",
      "Brake fluid",
      "Handbrake",
      "Parking brake",
      "Brake cables",
      "Brake adjustment",
      "Wheel alignment",
      "Toe setting",
    ],
    "Suspension & Steering": [
      "Front suspension",
      "Rear suspension",
      "Shock absorbers",
      "Springs",
      "Struts",
      "McPherson struts",
      "Coil springs",
      "Leaf springs",
      "Torsion bars",
      "Anti-roll bars",
      "Stabilizer links",
      "Ball joints",
      "Control arms",
      "Bushings",
      "Rubber mounts",
      "Steering box",
      "Steering rack",
      "Tie rods",
      "Track rods",
      "Steering wheel",
      "Steering column",
      "Universal joint",
      "Steering damper",
      "Power steering",
      "PS pump",
      "PS fluid",
      "PS belt",
      "PS hoses",
      "Steering lock",
      "Ignition lock",
      "Steering play",
      "Wheel alignment",
      "Front wheels",
      "Rear wheels",
      "Tire condition",
      "Tire pressure",
      "Wheel balance",
      "Rim condition",
      "Valve stems",
      "Tire tread",
      "Sidewall condition",
      "Tire age",
      "Spare tire",
      "Jack",
      "Tools",
      "Lug nuts",
      "Wheel bolts",
      "Hub caps",
      "Center caps",
      "Wheel covers",
      "Mud flaps",
      "Splash guards",
      "Fender liners",
      "Wheel wells",
      "Suspension travel",
      "Ride height",
      "Ground clearance",
      "Approach angle",
      "Departure angle",
      "Breakover angle",
    ],
    "Braking System": [
      "Front brakes",
      "Rear brakes",
      "Brake pads",
      "Brake shoes",
      "Brake discs",
      "Brake drums",
      "Brake calipers",
      "Wheel cylinders",
      "Master cylinder",
      "Brake booster",
      "Vacuum booster",
      "Brake fluid",
      "Brake lines",
      "Brake hoses",
      "Brake pedal",
      "Handbrake",
      "Parking brake",
      "Brake cables",
      "Brake adjustment",
      "ABS system",
      "ABS sensors",
      "ABS rings",
      "ABS module",
      "ABS pump",
      "Brake assist",
      "EBD system",
      "Brake balance",
      "Brake bias",
      "Proportioning valve",
      "Load sensing valve",
      "Brake warning light",
      "Brake fluid level",
      "Brake fluid quality",
      "Brake bleeding",
      "Brake noise",
      "Brake vibration",
      "Brake fade",
      "Brake efficiency",
      "Stopping distance",
      "Brake feel",
    ],
    "Electrical System": [
      "Battery",
      "Alternator",
      "Starter motor",
      "Ignition system",
      "Lighting system",
      "Headlights",
      "Tail lights",
      "Brake lights",
      "Turn signals",
      "Hazard lights",
      "Interior lights",
      "Dashboard lights",
      "Warning lights",
      "Horn",
      "Wiper motor",
      "Washer pump",
      "Fuel pump",
      "Cooling fan",
      "AC compressor",
      "Heater blower",
      "Instrument cluster",
      "Speedometer",
      "Odometer",
      "Fuel gauge",
      "Temperature gauge",
      "Oil pressure gauge",
      "Voltmeter",
      "Tachometer",
      "Clock",
      "Trip meter",
      "Warning buzzers",
      "Chimes",
      "Relays",
      "Fuses",
      "Circuit breakers",
      "Wiring harness",
      "Connectors",
      "Terminals",
      "Ground straps",
      "Switches",
      "Sensors",
      "ECU",
      "PCM",
      "BCM",
      "ABS module",
      "Airbag module",
      "Immobilizer",
      "Central locking",
      "Power windows",
      "Power mirrors",
    ],
    "Body & Interior": [
      "Body panels",
      "Paint condition",
      "Rust spots",
      "Dents",
      "Scratches",
      "Doors",
      "Door handles",
      "Door locks",
      "Windows",
      "Windshield",
      "Mirrors",
      "Bumpers",
      "Grille",
      "Hood",
      "Trunk",
      "Tailgate",
      "Roof",
      "Pillars",
      "Seats",
      "Seat belts",
      "Dashboard",
      "Steering wheel",
      "Gear knob",
      "Handbrake lever",
      "Pedals",
      "Floor mats",
      "Headliner",
      "Sun visors",
      "Glove box",
      "Storage compartments",
    ],
  },
  "4 Wheeler - Cars": {
    "Engine & Performance": [
      "Engine oil level & quality",
      "Coolant level & condition",
      "Air filter condition",
      "Fuel system check",
      "Fuel injection system",
      "Exhaust system inspection",
      "Engine mounting check",
      "Cooling system operation",
      "Radiator condition",
      "Cooling fan operation",
      "Thermostat function",
      "Water pump operation",
      "Coolant hoses",
      "Timing belt/chain condition",
      "Valve clearance adjustment",
      "Engine compression test",
      "Oil pressure check",
      "Fuel pressure test",
      "Throttle response",
      "Idle quality check",
      "Engine noise analysis",
      "Vibration check",
      "Emission test",
      "Turbocharger inspection",
      "Intercooler condition",
      "Boost pressure test",
      "Wastegate operation",
      "Blow-off valve function",
      "Intake manifold",
      "Exhaust manifold",
      "EGR valve operation",
      "PCV system check",
      "Crankcase ventilation",
      "Oil separator condition",
      "Fuel rail inspection",
      "Fuel injector test",
      "Throttle body cleaning",
      "MAP sensor test",
      "MAF sensor calibration",
      "IAT sensor check",
      "ECT sensor test",
      "TPS calibration",
      "O2 sensor function",
      "Knock sensor test",
      "Cam position sensor",
      "Crank position sensor",
      "ECU diagnostics",
      "Wiring harness inspection",
      "Ground point check",
      "Ignition coil test",
      "Spark plug condition",
      "Ignition timing",
      "Fuel pump operation",
      "Fuel filter condition",
      "Air intake inspection",
      "Exhaust pipe condition",
      "Catalytic converter test",
      "Muffler inspection",
      "DPF system check",
      "AdBlue system test",
      "SCR system operation",
      "Engine bay cleanliness",
      "Oil leak detection",
      "Coolant leak check",
      "Fuel leak inspection",
      "Vacuum leak test",
      "Boost leak check",
      "Drive belt condition",
      "Pulley alignment",
      "Belt tensioner",
      "Idler pulley",
      "Alternator test",
      "AC compressor check",
      "Power steering pump",
      "Brake booster vacuum",
      "EVAP system test",
      "Carbon canister",
      "Purge valve",
      "Vent valve",
      "Fuel tank pressure",
    ],
    "Transmission & Drivetrain": [
      "Clutch operation test",
      "Gear shifting smoothness",
      "Transmission fluid level",
      "Transmission fluid quality",
      "Differential oil check",
      "Transfer case oil",
      "Drive shaft inspection",
      "CV joint condition",
      "Universal joint test",
      "Clutch pedal adjustment",
      "Gear lever operation",
      "Shift cable condition",
      "Clutch cable adjustment",
      "Flywheel inspection",
      "Pressure plate condition",
      "Clutch disc wear",
      "Release bearing test",
      "Pilot bearing check",
      "Transmission case inspection",
      "Gear teeth condition",
      "Synchronizer operation",
      "Shift fork condition",
      "Shift rail inspection",
      "Detent mechanism",
      "Spring condition",
      "Seal integrity",
      "Gasket condition",
      "Input shaft bearing",
      "Output shaft bearing",
      "Layshaft bearing",
      "Reverse gear operation",
      "Final drive inspection",
      "Ring gear condition",
      "Pinion gear wear",
      "Differential case",
      "Side gear condition",
      "Spider gear wear",
      "Axle shaft inspection",
      "Wheel bearing test",
      "Hub assembly check",
      "Constant velocity joint",
      "Tripod joint",
      "Boot condition",
      "Grease condition",
      "Driveshaft balance",
      "Propeller shaft",
      "Center bearing",
      "Flex disc",
      "Guibo condition",
      "Transmission mount",
      "Engine mount",
      "Differential mount",
      "Torque converter test",
      "Valve body operation",
      "Solenoid function",
      "Pressure test",
      "Shift quality",
      "Lock-up operation",
      "Fluid cooler",
      "Filter condition",
    ],
    "Suspension & Steering": [
      "Front suspension inspection",
      "Rear suspension check",
      "Shock absorber test",
      "Spring condition",
      "Strut assembly",
      "McPherson strut test",
      "Coil spring inspection",
      "Leaf spring condition",
      "Torsion bar adjustment",
      "Anti-roll bar check",
      "Stabilizer link test",
      "Ball joint inspection",
      "Control arm condition",
      "Bushing wear check",
      "Rubber mount inspection",
      "Steering box test",
      "Steering rack inspection",
      "Tie rod end check",
      "Track rod condition",
      "Steering wheel play",
      "Steering column test",
      "Universal joint check",
      "Steering damper test",
      "Power steering operation",
      "PS pump test",
      "PS fluid level",
      "PS belt condition",
      "PS hose inspection",
      "Steering lock test",
      "Ignition lock check",
      "Wheel alignment",
      "Front toe setting",
      "Rear toe adjustment",
      "Camber angle check",
      "Caster angle test",
      "King pin inclination",
      "Thrust angle",
      "Steering geometry",
      "Turning radius test",
      "Front wheel inspection",
      "Rear wheel check",
      "Tire condition assessment",
      "Tire pressure check",
      "Wheel balance test",
      "Rim condition",
      "Valve stem inspection",
      "Tire tread measurement",
      "Sidewall condition",
      "Tire age verification",
      "Spare tire check",
      "Jack inspection",
      "Tool kit check",
      "Lug nut torque",
      "Wheel bolt inspection",
      "Hub cap condition",
      "Center cap check",
      "Wheel cover inspection",
      "Mud flap condition",
      "Splash guard check",
      "Fender liner inspection",
      "Wheel well condition",
      "Suspension travel test",
      "Ride height measurement",
      "Ground clearance check",
      "Approach angle",
      "Departure angle",
      "Breakover angle",
      "Articulation test",
      "Flex measurement",
      "Compression damping",
    ],
    "Braking System": [
      "Front brake inspection",
      "Rear brake check",
      "Brake pad thickness",
      "Brake shoe condition",
      "Brake disc inspection",
      "Brake drum condition",
      "Brake caliper test",
      "Wheel cylinder check",
      "Master cylinder inspection",
      "Brake booster test",
      "Vacuum booster check",
      "Brake fluid level",
      "Brake fluid quality",
      "Brake line inspection",
      "Brake hose condition",
      "Brake pedal test",
      "Handbrake operation",
      "Parking brake test",
      "Brake cable condition",
      "Brake adjustment check",
      "ABS system test",
      "ABS sensor check",
      "ABS ring inspection",
      "ABS module test",
      "ABS pump operation",
      "Brake assist test",
      "EBD system check",
      "ESP operation",
      "Brake balance test",
      "Brake bias check",
      "Proportioning valve",
      "Load sensing valve",
      "Brake warning light",
      "Brake fluid sensor",
      "Brake pad sensor",
      "Brake wear indicator",
      "Brake noise check",
      "Brake vibration test",
      "Brake fade test",
      "Brake efficiency",
      "Stopping distance",
      "Brake feel test",
      "Pedal travel check",
      "Brake force distribution",
      "Emergency brake test",
      "Hill hold assist",
      "Auto hold function",
      "Electronic parking brake",
      "Brake by wire",
      "Regenerative braking",
    ],
    "Electrical & Electronics": [
      "Battery condition test",
      "Alternator output",
      "Starter motor test",
      "Ignition system check",
      "Lighting system test",
      "Headlight operation",
      "Tail light function",
      "Brake light test",
      "Turn signal check",
      "Hazard light test",
      "Interior light check",
      "Dashboard illumination",
      "Warning light test",
      "Horn operation",
      "Wiper motor test",
      "Washer pump check",
      "Fuel pump test",
      "Cooling fan operation",
      "AC compressor test",
      "Heater blower check",
      "Instrument cluster test",
      "Speedometer accuracy",
      "Odometer function",
      "Fuel gauge test",
      "Temperature gauge check",
      "Oil pressure gauge",
      "Voltmeter test",
      "Tachometer check",
      "Clock function",
      "Trip meter test",
      "Warning buzzer check",
      "Chime operation",
      "Relay function",
      "Fuse condition",
      "Circuit breaker test",
      "Wiring harness inspection",
      "Connector check",
      "Terminal condition",
      "Ground strap test",
      "Switch operation",
    ],
  },
  "4 Wheeler - Commercial Cars": {
    "Engine & Performance": [
      "Heavy duty engine oil analysis",
      "Commercial coolant system",
      "Heavy duty air filtration",
      "Commercial fuel system",
      "Heavy duty injection system",
      "Commercial exhaust system",
      "Heavy duty engine mounting",
      "Commercial cooling operation",
      "Heavy duty radiator",
      "Commercial cooling fan",
      "Heavy duty thermostat",
      "Commercial water pump",
      "Heavy duty hoses",
      "Commercial timing system",
      "Heavy duty valve system",
      "Commercial compression test",
      "Heavy duty oil pressure",
      "Commercial fuel pressure",
      "Heavy duty throttle system",
      "Commercial idle system",
      "Heavy duty noise analysis",
      "Commercial vibration check",
      "Heavy duty emission test",
      "Commercial turbo system",
      "Heavy duty intercooler",
      "Commercial boost system",
      "Heavy duty wastegate",
      "Commercial blow-off system",
      "Heavy duty intake manifold",
      "Commercial exhaust manifold",
      "Heavy duty EGR system",
      "Commercial PCV system",
      "Heavy duty ventilation",
      "Commercial oil separator",
      "Heavy duty fuel rail",
      "Commercial injector system",
      "Heavy duty throttle body",
      "Commercial sensor systems",
      "Heavy duty ECU diagnostics",
      "Commercial wiring harness",
      "Heavy duty ignition system",
      "Commercial fuel pump",
      "Heavy duty filtration",
      "Commercial intake system",
      "Heavy duty exhaust pipe",
      "Commercial catalytic system",
      "Heavy duty muffler",
      "Commercial DPF system",
      "Heavy duty AdBlue system",
      "Commercial SCR system",
      "Heavy duty engine bay",
      "Commercial leak detection",
      "Heavy duty belt system",
      "Commercial pulley system",
      "Heavy duty tensioner",
      "Commercial alternator",
      "Heavy duty AC system",
      "Commercial power steering",
      "Heavy duty brake booster",
      "Commercial EVAP system",
      "Heavy duty carbon system",
      "Commercial valve system",
      "Heavy duty tank system",
    ],
    "Transmission & Drivetrain": [
      "Heavy duty clutch system",
      "Commercial gear system",
      "Heavy duty transmission fluid",
      "Commercial differential oil",
      "Heavy duty drive shaft",
      "Commercial CV joints",
      "Heavy duty universal joints",
      "Commercial clutch pedal",
      "Heavy duty gear lever",
      "Commercial shift system",
      "Heavy duty flywheel",
      "Commercial pressure plate",
      "Heavy duty clutch disc",
      "Commercial bearing system",
      "Heavy duty transmission case",
      "Commercial gear teeth",
      "Heavy duty synchronizers",
      "Commercial shift mechanism",
      "Heavy duty spring system",
      "Commercial seal system",
      "Heavy duty shaft system",
      "Commercial final drive",
      "Heavy duty ring gear",
      "Commercial pinion system",
      "Heavy duty differential",
      "Commercial axle system",
      "Heavy duty wheel bearings",
      "Commercial hub system",
      "Heavy duty CV system",
      "Commercial boot system",
      "Heavy duty grease system",
      "Commercial balance system",
      "Heavy duty mounting system",
      "Commercial torque converter",
      "Heavy duty valve body",
      "Commercial solenoid system",
      "Heavy duty pressure system",
      "Commercial shift quality",
      "Heavy duty cooler system",
      "Commercial filter system",
    ],
    "Suspension & Steering": [
      "Heavy duty front suspension",
      "Commercial rear suspension",
      "Heavy duty shock system",
      "Commercial spring system",
      "Heavy duty strut system",
      "Commercial coil springs",
      "Heavy duty leaf springs",
      "Commercial torsion system",
      "Heavy duty anti-roll system",
      "Commercial stabilizer system",
      "Heavy duty ball joints",
      "Commercial control arms",
      "Heavy duty bushing system",
      "Commercial steering box",
      "Heavy duty steering rack",
      "Commercial tie rod system",
      "Heavy duty steering wheel",
      "Commercial steering column",
      "Heavy duty power steering",
      "Commercial PS system",
      "Heavy duty alignment system",
      "Commercial wheel system",
      "Heavy duty tire system",
      "Commercial rim system",
      "Heavy duty valve system",
      "Commercial tread system",
      "Heavy duty sidewall",
      "Commercial tire age",
      "Heavy duty spare system",
      "Commercial tool system",
      "Heavy duty lug system",
      "Commercial hub system",
      "Heavy duty suspension travel",
      "Commercial ride height",
      "Heavy duty ground clearance",
      "Commercial angle system",
    ],
    "Braking System": [
      "Heavy duty front brakes",
      "Commercial rear brakes",
      "Heavy duty brake pads",
      "Commercial brake shoes",
      "Heavy duty brake discs",
      "Commercial brake drums",
      "Heavy duty calipers",
      "Commercial wheel cylinders",
      "Heavy duty master cylinder",
      "Commercial brake booster",
      "Heavy duty brake fluid",
      "Commercial brake lines",
      "Heavy duty brake hoses",
      "Commercial brake pedal",
      "Heavy duty handbrake",
      "Commercial ABS system",
      "Heavy duty ABS sensors",
      "Commercial ABS module",
      "Heavy duty brake assist",
      "Commercial EBD system",
      "Heavy duty brake balance",
      "Commercial proportioning valve",
      "Heavy duty warning system",
      "Commercial brake efficiency",
      "Heavy duty stopping distance",
      "Commercial brake feel",
      "Heavy duty emergency brake",
      "Commercial parking brake",
      "Heavy duty brake monitoring",
    ],
    "Electrical & Electronics": [
      "Heavy duty battery system",
      "Commercial alternator",
      "Heavy duty starter system",
      "Commercial ignition system",
      "Heavy duty lighting system",
      "Commercial headlight system",
      "Heavy duty warning system",
      "Commercial horn system",
      "Heavy duty wiper system",
      "Commercial fuel pump",
      "Heavy duty cooling fan",
      "Commercial AC system",
      "Heavy duty instrument cluster",
      "Commercial gauge system",
      "Heavy duty warning system",
      "Commercial relay system",
      "Heavy duty fuse system",
      "Commercial wiring system",
      "Heavy duty connector system",
      "Commercial ground system",
    ],
  },
  "4 Wheeler - Trucks": {
    "Engine & Performance": [
      "Heavy duty diesel engine",
      "Commercial turbo system",
      "Heavy duty cooling system",
      "Commercial fuel injection",
      "Heavy duty exhaust system",
      "Commercial engine management",
      "Heavy duty lubrication",
      "Commercial air system",
      "Heavy duty mounting system",
      "Commercial emission control",
      "Heavy duty oil analysis",
      "Commercial coolant system",
      "Heavy duty air filtration",
      "Commercial fuel system",
      "Heavy duty injection timing",
      "Commercial exhaust treatment",
      "Heavy duty engine mounting",
      "Commercial cooling operation",
      "Heavy duty radiator system",
      "Commercial fan system",
      "Heavy duty thermostat",
      "Commercial water pump",
      "Heavy duty hose system",
      "Commercial timing system",
      "Heavy duty valve system",
      "Commercial compression test",
      "Heavy duty oil pressure",
      "Commercial fuel pressure",
      "Heavy duty throttle system",
      "Commercial idle system",
      "Heavy duty noise analysis",
      "Commercial vibration check",
      "Heavy duty emission test",
      "Commercial turbo system",
      "Heavy duty intercooler",
      "Commercial boost system",
      "Heavy duty wastegate",
      "Commercial blow-off system",
      "Heavy duty intake system",
      "Commercial exhaust system",
      "Heavy duty EGR system",
      "Commercial PCV system",
      "Heavy duty ventilation",
      "Commercial oil separator",
      "Heavy duty fuel rail",
      "Commercial injector system",
      "Heavy duty throttle body",
      "Commercial sensor systems",
      "Heavy duty ECU diagnostics",
      "Commercial wiring harness",
      "Heavy duty ignition system",
      "Commercial fuel pump",
      "Heavy duty filtration",
      "Commercial intake system",
      "Heavy duty exhaust pipe",
      "Commercial catalytic system",
      "Heavy duty muffler",
      "Commercial DPF system",
      "Heavy duty AdBlue system",
      "Commercial SCR system",
      "Heavy duty engine bay",
      "Commercial leak detection",
      "Heavy duty belt system",
      "Commercial pulley system",
      "Heavy duty tensioner",
      "Commercial alternator",
      "Heavy duty AC system",
      "Commercial power steering",
      "Heavy duty brake booster",
      "Commercial EVAP system",
      "Heavy duty carbon system",
      "Commercial valve system",
      "Heavy duty tank system",
    ],
    "Transmission & Drivetrain": [
      "Heavy duty transmission",
      "Commercial clutch system",
      "Heavy duty gear system",
      "Commercial differential",
      "Heavy duty drive system",
      "Commercial axle system",
      "Heavy duty transmission fluid",
      "Commercial differential oil",
      "Heavy duty drive shaft",
      "Commercial CV joints",
      "Heavy duty universal joints",
      "Commercial clutch pedal",
      "Heavy duty gear lever",
      "Commercial shift system",
      "Heavy duty flywheel",
      "Commercial pressure plate",
      "Heavy duty clutch disc",
      "Commercial bearing system",
      "Heavy duty transmission case",
      "Commercial gear teeth",
      "Heavy duty synchronizers",
      "Commercial shift mechanism",
      "Heavy duty spring system",
      "Commercial seal system",
      "Heavy duty shaft system",
      "Commercial final drive",
      "Heavy duty ring gear",
      "Commercial pinion system",
      "Heavy duty differential",
      "Commercial axle system",
      "Heavy duty wheel bearings",
      "Commercial hub system",
      "Heavy duty CV system",
      "Commercial boot system",
      "Heavy duty grease system",
      "Commercial balance system",
      "Heavy duty mounting system",
      "Commercial torque converter",
      "Heavy duty valve body",
      "Commercial solenoid system",
      "Heavy duty pressure system",
      "Commercial shift quality",
      "Heavy duty cooler system",
      "Commercial filter system",
    ],
    "Suspension & Steering": [
      "Heavy duty front suspension",
      "Commercial rear suspension",
      "Heavy duty shock system",
      "Commercial spring system",
      "Heavy duty leaf springs",
      "Commercial air suspension",
      "Heavy duty stabilizer system",
      "Commercial steering system",
      "Heavy duty power steering",
      "Commercial wheel system",
      "Heavy duty tire system",
      "Commercial alignment system",
      "Heavy duty suspension travel",
      "Commercial ride height",
      "Heavy duty ground clearance",
      "Commercial load capacity",
      "Heavy duty articulation",
      "Commercial stability system",
    ],
    "Braking System": [
      "Heavy duty air brakes",
      "Commercial brake system",
      "Heavy duty brake chambers",
      "Commercial air compressor",
      "Heavy duty air tanks",
      "Commercial brake valves",
      "Heavy duty brake lines",
      "Commercial brake controls",
      "Heavy duty ABS system",
      "Commercial brake monitoring",
      "Heavy duty brake efficiency",
      "Commercial stopping distance",
      "Heavy duty emergency brakes",
      "Commercial parking brakes",
      "Heavy duty brake maintenance",
    ],
    "Electrical & Electronics": [
      "Heavy duty electrical system",
      "Commercial battery system",
      "Heavy duty alternator",
      "Commercial lighting system",
      "Heavy duty control system",
      "Commercial wiring system",
      "Heavy duty monitoring system",
      "Commercial diagnostic system",
      "Heavy duty safety system",
      "Commercial communication system",
    ],
  },
  "6 Wheeler": {
    "Heavy Duty Engine": [
      "Heavy duty diesel engine analysis",
      "Commercial turbocharger system",
      "Heavy duty cooling capacity",
      "Commercial fuel injection system",
      "Heavy duty exhaust treatment",
      "Commercial engine management",
      "Heavy duty lubrication system",
      "Commercial air intake system",
      "Heavy duty mounting system",
      "Commercial emission control",
      "Heavy duty oil analysis",
      "Commercial coolant system",
      "Heavy duty air filtration",
      "Commercial fuel system",
      "Heavy duty injection timing",
      "Commercial exhaust treatment",
      "Heavy duty engine mounting",
      "Commercial cooling operation",
      "Heavy duty radiator system",
      "Commercial fan system",
      "Heavy duty thermostat",
      "Commercial water pump",
      "Heavy duty hose system",
      "Commercial timing system",
      "Heavy duty valve system",
      "Commercial compression test",
      "Heavy duty oil pressure",
      "Commercial fuel pressure",
      "Heavy duty throttle system",
      "Commercial idle system",
      "Heavy duty noise analysis",
      "Commercial vibration check",
      "Heavy duty emission test",
      "Commercial turbo system",
      "Heavy duty intercooler",
      "Commercial boost system",
      "Heavy duty wastegate",
      "Commercial blow-off system",
      "Heavy duty intake system",
      "Commercial exhaust system",
      "Heavy duty EGR system",
      "Commercial PCV system",
      "Heavy duty ventilation",
      "Commercial oil separator",
      "Heavy duty fuel rail",
      "Commercial injector system",
      "Heavy duty throttle body",
      "Commercial sensor systems",
      "Heavy duty ECU diagnostics",
      "Commercial wiring harness",
      "Heavy duty ignition system",
      "Commercial fuel pump",
      "Heavy duty filtration",
      "Commercial intake system",
      "Heavy duty exhaust pipe",
      "Commercial catalytic system",
      "Heavy duty muffler",
      "Commercial DPF system",
      "Heavy duty AdBlue system",
      "Commercial SCR system",
      "Heavy duty engine bay",
      "Commercial leak detection",
      "Heavy duty belt system",
      "Commercial pulley system",
      "Heavy duty tensioner",
      "Commercial alternator",
      "Heavy duty AC system",
      "Commercial power steering",
      "Heavy duty brake booster",
      "Commercial EVAP system",
      "Commercial carbon system",
      "Commercial valve system",
      "Heavy duty tank system",
      "Commercial fuel management",
      "Heavy duty performance test",
      "Commercial efficiency test",
      "Heavy duty load test",
      "Commercial durability test",
      "Heavy duty maintenance check",
      "Commercial service interval",
      "Heavy duty warranty check",
      "Commercial compliance test",
      "Heavy duty safety check",
      "Commercial reliability test",
      "Heavy duty longevity test",
      "Commercial performance optimization",
      "Heavy duty fuel economy",
      "Commercial power output",
      "Heavy duty torque test",
      "Commercial acceleration test",
      "Heavy duty top speed",
      "Commercial grade ability",
      "Heavy duty towing capacity",
    ],
    "Commercial Transmission": [
      "Heavy duty transmission system",
      "Commercial clutch system",
      "Heavy duty gear system",
      "Commercial differential system",
      "Heavy duty drive system",
      "Commercial axle system",
      "Heavy duty transmission controls",
      "Commercial cooling system",
      "Heavy duty lubrication system",
      "Commercial transmission fluid",
      "Heavy duty differential oil",
      "Commercial drive shaft",
      "Heavy duty CV joints",
      "Commercial universal joints",
      "Heavy duty clutch pedal",
      "Commercial gear lever",
      "Heavy duty shift system",
      "Commercial flywheel",
      "Heavy duty pressure plate",
      "Commercial clutch disc",
      "Heavy duty bearing system",
      "Commercial transmission case",
      "Heavy duty gear teeth",
      "Commercial synchronizers",
      "Heavy duty shift mechanism",
      "Commercial spring system",
      "Heavy duty seal system",
      "Commercial shaft system",
      "Heavy duty final drive",
      "Commercial ring gear",
      "Heavy duty pinion system",
      "Commercial differential",
      "Heavy duty axle system",
      "Commercial wheel bearings",
      "Heavy duty hub system",
      "Commercial CV system",
      "Heavy duty boot system",
      "Commercial grease system",
      "Heavy duty balance system",
      "Commercial mounting system",
      "Heavy duty torque converter",
      "Commercial valve body",
      "Heavy duty solenoid system",
      "Commercial pressure system",
      "Heavy duty shift quality",
      "Commercial cooler system",
      "Heavy duty filter system",
      "Commercial maintenance check",
      "Heavy duty service interval",
      "Commercial warranty check",
      "Heavy duty compliance test",
      "Commercial safety check",
      "Heavy duty reliability test",
      "Commercial longevity test",
      "Heavy duty performance optimization",
      "Commercial efficiency test",
      "Heavy duty load test",
      "Commercial durability test",
      "Heavy duty gear ratio",
      "Commercial torque capacity",
      "Heavy duty speed range",
      "Commercial shift pattern",
      "Heavy duty clutch capacity",
      "Commercial differential ratio",
      "Heavy duty axle capacity",
      "Commercial load rating",
      "Heavy duty towing capacity",
      "Commercial grade ability",
      "Heavy duty acceleration",
      "Commercial top speed",
      "Heavy duty fuel economy",
      "Commercial power transmission",
      "Heavy duty torque multiplication",
      "Commercial gear reduction",
      "Heavy duty overdrive",
      "Commercial reverse gear",
      "Heavy duty parking lock",
      "Commercial neutral safety",
    ],
    "Heavy Duty Suspension": [
      "Commercial leaf spring system",
      "Heavy duty shock absorber system",
      "Commercial stabilizer system",
      "Heavy duty steering system",
      "Commercial wheel system",
      "Heavy duty tire system",
      "Commercial alignment system",
      "Heavy duty front axle suspension",
      "Commercial rear axle suspension",
      "Heavy duty steering system",
      "Commercial power steering",
      "Heavy duty leaf springs",
      "Commercial shock absorbers",
      "Heavy duty stabilizer bars",
      "Commercial ball joints",
      "Heavy duty control arms",
      "Commercial bushings",
      "Heavy duty rubber mounts",
      "Commercial steering box",
      "Heavy duty steering rack",
      "Commercial tie rods",
      "Heavy duty track rods",
      "Commercial steering wheel",
      "Heavy duty steering column",
      "Commercial universal joint",
      "Heavy duty steering damper",
      "Commercial power steering",
      "Heavy duty PS pump",
      "Commercial PS fluid",
      "Heavy duty PS belt",
      "Commercial PS hoses",
      "Heavy duty steering lock",
      "Commercial ignition lock",
      "Heavy duty wheel alignment",
      "Commercial front wheels",
      "Heavy duty rear wheels",
      "Commercial tire condition",
      "Heavy duty tire pressure",
      "Commercial wheel balance",
      "Heavy duty rim condition",
      "Commercial valve stems",
      "Heavy duty tire tread",
      "Commercial sidewall condition",
      "Heavy duty tire age",
      "Commercial spare tire",
      "Heavy duty jack",
      "Commercial tools",
      "Heavy duty lug nuts",
      "Commercial wheel bolts",
      "Commercial hub caps",
      "Commercial center caps",
      "Heavy duty wheel covers",
      "Commercial mud flaps",
      "Heavy duty splash guards",
      "Commercial fender liners",
      "Heavy duty wheel wells",
      "Commercial suspension travel",
      "Heavy duty ride height",
      "Commercial ground clearance",
      "Heavy duty load distribution",
    ],
    "Air Brake System": [
      "Air brake system",
      "Service brakes",
      "Parking brake",
      "ABS system",
      "Air compressor systems",
      "Air tank systems",
      "Brake valve systems",
      "Air line systems",
      "Brake chamber systems",
      "Commercial brake controls",
      "Air brake safety systems",
      "Heavy duty air compressor",
      "Commercial air tanks",
      "Heavy duty brake valves",
      "Commercial air lines",
      "Heavy duty brake chambers",
      "Commercial brake controls",
      "Heavy duty safety systems",
      "Commercial brake monitoring",
      "Heavy duty brake efficiency",
      "Commercial stopping distance",
      "Heavy duty emergency brakes",
      "Commercial parking brakes",
      "Heavy duty brake maintenance",
      "Commercial brake adjustment",
      "Heavy duty brake inspection",
      "Commercial brake testing",
      "Heavy duty brake certification",
      "Commercial brake compliance",
      "Heavy duty brake safety",
      "Commercial brake reliability",
      "Heavy duty brake durability",
      "Commercial brake performance",
      "Heavy duty brake optimization",
      "Commercial brake service",
      "Heavy duty brake repair",
      "Commercial brake replacement",
      "Heavy duty brake upgrade",
      "Commercial brake modification",
      "Heavy duty brake calibration",
      "Commercial brake validation",
      "Heavy duty brake verification",
      "Commercial brake documentation",
      "Heavy duty brake training",
      "Commercial brake support",
      "Heavy duty brake warranty",
      "Commercial brake guarantee",
      "Heavy duty brake insurance",
      "Commercial brake liability",
      "Heavy duty brake responsibility",
      "Commercial brake accountability",
    ],
    "Commercial Electrical": [
      "Heavy duty battery systems",
      "Commercial charging systems",
      "Heavy duty lighting systems",
      "Commercial control systems",
      "Heavy duty wiring systems",
      "Commercial electrical system",
      "Heavy duty battery system",
      "Commercial alternator",
      "Heavy duty starter system",
      "Commercial ignition system",
      "Heavy duty lighting system",
      "Commercial headlight system",
      "Heavy duty warning system",
      "Commercial horn system",
      "Heavy duty wiper system",
      "Commercial fuel pump",
      "Heavy duty cooling fan",
      "Commercial AC system",
      "Heavy duty instrument cluster",
      "Commercial gauge system",
      "Heavy duty warning system",
      "Commercial relay system",
      "Heavy duty fuse system",
      "Commercial wiring system",
      "Heavy duty connector system",
      "Commercial ground system",
      "Heavy duty monitoring system",
      "Commercial diagnostic system",
      "Heavy duty safety system",
      "Commercial communication system",
    ],
  },
  "More Than 8 Wheelers": {
    "Heavy Duty Engine": [
      "Ultra heavy duty engine systems",
      "Large displacement diesel engines",
      "Multiple turbocharger systems",
      "Heavy duty cooling systems",
      "Commercial fuel injection systems",
      "Heavy duty exhaust systems",
      "Advanced engine management",
      "Heavy duty lubrication systems",
      "Commercial air systems",
      "Heavy duty mounting systems",
      "Advanced emission controls",
      "Ultra heavy duty diesel engine analysis",
      "Commercial multiple turbocharger system",
      "Heavy duty cooling capacity",
      "Commercial fuel injection system",
      "Heavy duty exhaust treatment",
      "Commercial engine management",
      "Heavy duty lubrication system",
      "Commercial air intake system",
      "Heavy duty mounting system",
      "Commercial emission control",
      "Heavy duty oil analysis",
      "Commercial coolant system",
      "Heavy duty air filtration",
      "Commercial fuel system",
      "Heavy duty injection timing",
      "Commercial exhaust treatment",
      "Heavy duty engine mounting",
      "Commercial cooling operation",
      "Heavy duty radiator system",
      "Commercial fan system",
      "Heavy duty thermostat",
      "Commercial water pump",
      "Heavy duty hose system",
      "Commercial timing system",
      "Heavy duty valve system",
      "Commercial compression test",
      "Heavy duty oil pressure",
      "Commercial fuel pressure",
      "Heavy duty throttle system",
      "Commercial idle system",
      "Heavy duty noise analysis",
      "Commercial vibration check",
      "Heavy duty emission test",
      "Commercial turbo system",
      "Heavy duty intercooler",
      "Commercial boost system",
      "Heavy duty wastegate",
      "Commercial blow-off system",
      "Heavy duty intake system",
      "Commercial exhaust system",
      "Heavy duty EGR system",
      "Commercial PCV system",
      "Heavy duty ventilation",
      "Commercial oil separator",
      "Heavy duty fuel rail",
      "Commercial injector system",
      "Heavy duty throttle body",
      "Commercial sensor systems",
      "Heavy duty ECU diagnostics",
      "Commercial wiring harness",
      "Heavy duty ignition system",
      "Commercial fuel pump",
      "Heavy duty filtration",
      "Commercial intake system",
      "Heavy duty exhaust pipe",
      "Commercial catalytic system",
      "Heavy duty muffler",
      "Commercial DPF system",
      "Heavy duty AdBlue system",
      "Commercial SCR system",
      "Heavy duty engine bay",
      "Commercial leak detection",
      "Heavy duty belt system",
      "Commercial pulley system",
      "Heavy duty tensioner",
      "Commercial alternator",
      "Heavy duty AC system",
      "Commercial power steering",
      "Heavy duty brake booster",
      "Commercial EVAP system",
      "Heavy duty carbon system",
      "Commercial valve system",
      "Heavy duty tank system",
      "Commercial fuel management",
      "Heavy duty performance test",
      "Commercial efficiency test",
      "Heavy duty load test",
      "Commercial durability test",
      "Heavy duty maintenance check",
      "Heavy duty service interval",
      "Heavy duty warranty check",
      "Commercial compliance test",
      "Heavy duty safety check",
      "Heavy duty reliability test",
      "Heavy duty longevity test",
      "Commercial performance optimization",
      "Heavy duty fuel economy",
      "Commercial power output",
      "Heavy duty torque test",
      "Commercial acceleration test",
      "Heavy duty top speed",
      "Commercial grade ability",
      "Heavy duty towing capacity",
      "Commercial payload capacity",
      "Heavy duty engine efficiency",
      "Commercial fuel consumption",
      "Heavy duty emission compliance",
      "Commercial environmental impact",
      "Heavy duty noise control",
      "Commercial vibration control",
      "Heavy duty thermal management",
      "Commercial cooling efficiency",
      "Heavy duty lubrication efficiency",
      "Commercial maintenance cost",
      "Heavy duty operating cost",
      "Commercial lifecycle cost",
      "Heavy duty reliability rating",
      "Commercial durability rating",
      "Heavy duty performance rating",
      "Commercial efficiency rating",
      "Heavy duty safety rating",
      "Commercial environmental rating",
      "Heavy duty quality rating",
      "Commercial customer satisfaction",
      "Heavy duty market acceptance",
      "Commercial competitive advantage",
    ],
    "Heavy Duty Transmission": [
      "Ultra heavy duty transmission",
      "Multi-axle drivetrain",
      "Transfer case",
      "Inter-axle differential",
      "Heavy duty transmission",
      "Multi-speed transmission systems",
      "Heavy duty differential systems",
      "Commercial drive systems",
      "Heavy duty axle systems",
      "Advanced transmission controls",
      "Heavy duty cooling systems",
      "Commercial lubrication systems",
      "Ultra heavy duty transmission system",
      "Commercial multi-axle drivetrain",
      "Heavy duty transfer case",
      "Commercial inter-axle differential",
      "Heavy duty transmission controls",
      "Commercial cooling system",
      "Heavy duty lubrication system",
      "Commercial transmission fluid",
      "Heavy duty differential oil",
      "Commercial drive shaft",
      "Heavy duty CV joints",
      "Commercial universal joints",
      "Heavy duty clutch pedal",
      "Commercial gear lever",
      "Heavy duty shift system",
      "Commercial flywheel",
      "Heavy duty pressure plate",
      "Commercial clutch disc",
      "Heavy duty bearing system",
      "Commercial transmission case",
      "Heavy duty gear teeth",
      "Commercial synchronizers",
      "Heavy duty shift mechanism",
      "Commercial spring system",
      "Heavy duty seal system",
      "Commercial shaft system",
      "Heavy duty final drive",
      "Commercial ring gear",
      "Heavy duty pinion system",
      "Commercial differential",
      "Heavy duty axle system",
      "Commercial wheel bearings",
      "Heavy duty hub system",
      "Commercial CV system",
      "Heavy duty boot system",
      "Commercial grease system",
      "Heavy duty balance system",
      "Commercial mounting system",
      "Heavy duty torque converter",
      "Commercial valve body",
      "Heavy duty solenoid system",
      "Commercial pressure system",
      "Heavy duty shift quality",
      "Commercial cooler system",
      "Heavy duty filter system",
      "Commercial maintenance check",
      "Heavy duty service interval",
      "Commercial warranty check",
      "Heavy duty compliance test",
      "Commercial safety check",
      "Heavy duty reliability test",
      "Commercial longevity test",
      "Heavy duty performance optimization",
      "Commercial efficiency test",
      "Heavy duty load test",
      "Commercial durability test",
      "Heavy duty gear ratio",
      "Commercial torque capacity",
      "Heavy duty speed range",
      "Commercial shift pattern",
      "Heavy duty clutch capacity",
      "Commercial differential ratio",
      "Heavy duty axle capacity",
      "Commercial load rating",
      "Heavy duty towing capacity",
      "Commercial grade ability",
      "Heavy duty acceleration",
      "Commercial top speed",
      "Heavy duty fuel economy",
      "Commercial power transmission",
    ],
    "Multi-Axle Suspension": [
      "Multi-axle suspension",
      "Air suspension system",
      "Steering geometry",
      "Power steering system",
      "Heavy duty multi-axle suspension",
      "Commercial air suspension system",
      "Heavy duty steering geometry",
      "Commercial power steering system",
      "Heavy duty load balancing",
      "Commercial suspension travel",
      "Heavy duty ride height",
      "Commercial ground clearance",
      "Heavy duty articulation",
      "Commercial stability system",
      "Heavy duty front axle suspension",
      "Commercial rear axle suspension",
      "Heavy duty steering system",
      "Commercial power steering",
      "Heavy duty leaf springs",
      "Commercial shock absorbers",
      "Heavy duty stabilizer bars",
      "Commercial ball joints",
      "Heavy duty control arms",
      "Commercial bushings",
      "Heavy duty rubber mounts",
      "Commercial steering box",
      "Heavy duty steering rack",
      "Commercial tie rods",
      "Heavy duty track rods",
      "Commercial steering wheel",
      "Heavy duty steering column",
      "Commercial universal joint",
      "Heavy duty steering damper",
      "Commercial power steering",
      "Heavy duty PS pump",
      "Commercial PS fluid",
      "Heavy duty PS belt",
      "Commercial PS hoses",
      "Heavy duty steering lock",
      "Commercial ignition lock",
      "Heavy duty wheel alignment",
      "Commercial front wheels",
      "Heavy duty rear wheels",
      "Commercial tire condition",
      "Heavy duty tire pressure",
      "Commercial wheel balance",
      "Heavy duty rim condition",
      "Commercial valve stems",
      "Heavy duty tire tread",
      "Commercial sidewall condition",
      "Heavy duty tire age",
      "Commercial spare tire",
      "Heavy duty jack",
      "Commercial tools",
      "Heavy duty lug nuts",
      "Commercial wheel bolts",
      "Heavy duty hub caps",
      "Commercial center caps",
    ],
    "Air Brake System": [
      "Air brake system",
      "Multi-circuit braking",
      "Retarder system",
      "ABS/EBS system",
      "Heavy duty air brake system",
      "Commercial multi-circuit braking",
      "Heavy duty retarder system",
      "Commercial ABS/EBS system",
      "Heavy duty brake performance test",
      "Commercial brake efficiency",
      "Heavy duty stopping distance",
      "Commercial emergency brakes",
      "Heavy duty parking brakes",
      "Commercial brake maintenance",
      "Heavy duty air compressor",
      "Commercial air tanks",
      "Heavy duty brake valves",
      "Commercial air lines",
      "Heavy duty brake chambers",
      "Commercial brake controls",
      "Heavy duty safety systems",
      "Commercial brake monitoring",
      "Heavy duty brake adjustment",
      "Commercial brake inspection",
      "Heavy duty brake testing",
      "Commercial brake certification",
      "Heavy duty brake compliance",
      "Heavy duty brake safety",
      "Heavy duty brake reliability",
      "Commercial brake durability",
      "Heavy duty brake performance",
      "Commercial brake optimization",
      "Heavy duty brake service",
      "Commercial brake repair",
      "Heavy duty brake replacement",
      "Commercial brake upgrade",
      "Heavy duty brake modification",
      "Heavy duty brake calibration",
      "Commercial brake validation",
      "Heavy duty brake verification",
      "Commercial brake documentation",
      "Heavy duty brake training",
      "Commercial brake support",
      "Heavy duty brake warranty",
      "Commercial brake guarantee",
      "Heavy duty brake insurance",
      "Heavy duty brake liability",
      "Commercial brake responsibility",
      "Heavy duty brake accountability",
      "Commercial brake performance test",
      "Heavy duty brake efficiency test",
      "Commercial brake safety test",
      "Heavy duty brake reliability test",
      "Commercial brake durability test",
      "Heavy duty brake compliance test",
      "Commercial brake certification test",
      "Heavy duty brake validation test",
      "Commercial brake verification test",
      "Heavy duty brake documentation test",
      "Commercial brake training test",
      "Heavy duty brake support test",
    ],
    "Electrical & Safety": [
      "24V electrical system",
      "Heavy-duty alternator",
      "Safety lighting",
      "Warning systems",
      "Emergency equipment",
      "Heavy duty 24V electrical system",
      "Commercial heavy-duty alternator",
      "Heavy duty safety lighting",
      "Commercial warning systems",
      "Heavy duty emergency equipment",
      "Commercial communication systems",
      "Heavy duty monitoring system",
      "Commercial diagnostic system",
      "Heavy duty safety system",
      "Commercial communication system",
      "Heavy duty electrical system",
      "Commercial battery system",
      "Heavy duty alternator",
      "Commercial lighting system",
      "Heavy duty control system",
      "Commercial wiring system",
      "Heavy duty monitoring system",
      "Commercial diagnostic system",
      "Heavy duty safety system",
      "Commercial communication system",
      "Heavy duty emergency system",
      "Commercial warning system",
      "Heavy duty alarm system",
      "Commercial notification system",
      "Heavy duty alert system",
    ],
    "Body & Cargo": [
      "Heavy-duty chassis",
      "Cargo securing",
      "Loading systems",
      "Structural integrity",
      "Weight distribution",
      "Cargo capacity",
      "Access systems",
      "Safety barriers",
      "Load monitoring",
      "Overall vehicle condition",
      "Heavy duty chassis",
      "Commercial cargo securing",
      "Heavy duty loading systems",
      "Commercial structural integrity",
      "Heavy duty weight distribution",
      "Commercial cargo capacity",
      "Heavy duty access systems",
      "Commercial safety barriers",
      "Heavy duty load monitoring",
      "Commercial overall vehicle condition",
    ],
  },
}

export default function ProductManagementPage() {
  const [editingProduct, setEditingProduct] = useState<VehicleProduct | null>(null)
  const [inspectingProduct, setInspectingProduct] = useState<VehicleProduct | null>(null)
  const [inspectionAnswers, setInspectionAnswers] = useState<Record<string, VehicleCondition>>({})
  const [customBasePrice, setCustomBasePrice] = useState<number>(0)
  const [vehicles, setVehicles] = useState(() => vehiclesDb.getAll())
  const [conditionPriceAdjustments, setConditionPriceAdjustments] = useState<Record<VehicleCondition, number>>({
    Excellent: 0,
    "Very Good": -2000,
    Good: -3000,
    Average: -4500,
    Poor: -6000,
  })

  const conditionPoints: Record<VehicleCondition, number> = {
    Excellent: 1.0,
    "Very Good": 0.8,
    Good: 0.6,
    Average: 0.4,
    Poor: 0.2,
  }

  const calculateAdjustedPrice = (basePrice: number, condition: VehicleCondition): number => {
    return Math.max(0, basePrice + conditionPriceAdjustments[condition])
  }

  const handleStartInspection = (product: VehicleProduct) => {
    if (product.serviceType !== "Sell") return

    setInspectingProduct(product)
    setCustomBasePrice(product.basePrice)

    // Load existing inspection results if available
    if (product.inspectionResults && product.inspectionResults.length > 0) {
      const existingAnswers: Record<string, VehicleCondition> = {}
      product.inspectionResults.forEach((result: any) => {
        existingAnswers[result.questionId] = result.condition
      })
      setInspectionAnswers(existingAnswers)
    } else {
      setInspectionAnswers({})
    }
  }

  const handleAnswerChange = (questionId: string, condition: VehicleCondition) => {
    setInspectionAnswers((prev) => ({
      ...prev,
      [questionId]: condition,
    }))
  }

  const calculateCurrentResults = () => {
    if (!inspectingProduct)
      return {
        totalScore: 0,
        maxScore: 0,
        condition: "Good" as VehicleCondition,
        adjustedPrice: 0,
      }

    const questions = inspectionQuestions[inspectingProduct.type as keyof typeof inspectionQuestions]
    if (!questions)
      return {
        totalScore: 0,
        maxScore: 0,
        condition: "Good" as VehicleCondition,
        adjustedPrice: 0,
      }

    let totalScore = 0
    let maxScore = 0

    Object.values(questions).forEach((categoryQuestions) => {
      categoryQuestions.forEach((_, index) => {
        const questionId = `${inspectingProduct.type}_${index + 1}`
        const condition = inspectionAnswers[questionId] || "Good"
        totalScore += Math.round(1 * conditionPoints[condition])
        maxScore += 1
      })
    })

    const percentage = maxScore > 0 ? (totalScore / maxScore) * 100 : 0
    let overallCondition: VehicleCondition = "Good"

    if (percentage >= 90) overallCondition = "Excellent"
    else if (percentage >= 75) overallCondition = "Very Good"
    else if (percentage >= 60) overallCondition = "Good"
    else if (percentage >= 45) overallCondition = "Average"
    else overallCondition = "Poor"

    const adjustedPrice = Math.round(calculateAdjustedPrice(customBasePrice, overallCondition))

    return { totalScore, maxScore, condition: overallCondition, adjustedPrice }
  }

  const handleSaveInspection = () => {
    if (!inspectingProduct) return

    const { totalScore, maxScore, condition, adjustedPrice } = calculateCurrentResults()

    const results = Object.entries(inspectionAnswers).map(([questionId, conditionValue]) => ({
      questionId,
      condition: conditionValue,
      points: Math.round(1 * conditionPoints[conditionValue]),
      maxPoints: 1,
    }))

    vehiclesDb.update(inspectingProduct.id, {
      basePrice: customBasePrice,
      condition,
      currentPrice: adjustedPrice,
      inspectionScore: totalScore,
      maxInspectionScore: maxScore,
      inspectionDate: new Date().toISOString(),
      inspectionResults: results,
    })

    setVehicles(vehiclesDb.getAll())
    setInspectingProduct(null)
    setInspectionAnswers({})
  }

  const { totalScore, maxScore, condition, adjustedPrice } = calculateCurrentResults()
  const completionPercentage = inspectingProduct
    ? (Object.keys(inspectionAnswers).length /
        Object.values(inspectionQuestions[inspectingProduct.type as keyof typeof inspectionQuestions] || {}).flat()
          .length) *
      100
    : 0

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Manage Products</h1>
      </div>

      {/* Edit Dialog */}
      <Dialog open={!!editingProduct} onOpenChange={() => setEditingProduct(null)}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Edit Vehicle</DialogTitle>
            <DialogDescription>Update the vehicle details below.</DialogDescription>
          </DialogHeader>
          {editingProduct && <ProductForm product={editingProduct} onSuccess={() => setEditingProduct(null)} />}
        </DialogContent>
      </Dialog>

      <ProductList onEdit={setEditingProduct} showServiceType={true} onInspect={handleStartInspection} />

      {/* 300-Point Inspection Section for Sell Service Type */}
      {inspectingProduct && inspectingProduct.serviceType === "Sell" && (
        <Card className="border-2 border-primary">
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>
                300-Point Inspection: {inspectingProduct.brand} {inspectingProduct.model}
              </CardTitle>
              <div className="flex gap-2">
                <Button onClick={handleSaveInspection} className="bg-green-600 hover:bg-green-700">
                  <Save className="h-4 w-4 mr-2" />
                  Save Inspection & Update Price
                </Button>
                <Button variant="outline" onClick={() => setInspectingProduct(null)}>
                  Cancel
                </Button>
              </div>
            </div>
            <Progress value={completionPercentage} className="w-full" />
            <div className="text-sm text-muted-foreground">
              {Object.keys(inspectionAnswers).length} /{" "}
              {
                Object.values(
                  inspectionQuestions[inspectingProduct.type as keyof typeof inspectionQuestions] || {},
                ).flat().length
              }{" "}
              questions completed
            </div>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Price and Results Summary */}
            <div className="grid grid-cols-2 md:grid-cols-5 gap-4 p-4 bg-muted rounded-lg">
              <div className="space-y-2">
                <Label htmlFor="basePrice">Base Price (₹)</Label>
                <Input
                  id="basePrice"
                  type="number"
                  value={customBasePrice}
                  onChange={(e) => setCustomBasePrice(Number(e.target.value))}
                  className="font-medium"
                />
              </div>
              <div className="text-center">
                <div className="text-sm text-muted-foreground">Current Score</div>
                <div className="text-2xl font-bold">
                  {totalScore}/{maxScore}
                </div>
              </div>
              <div className="text-center">
                <div className="text-sm text-muted-foreground">Condition</div>
                <Badge className={conditionColors[condition]}>{condition}</Badge>
              </div>
              <div className="text-center">
                <div className="text-sm text-muted-foreground">Adjusted Price</div>
                <div className="text-xl font-bold text-primary">₹{adjustedPrice.toLocaleString()}</div>
              </div>
              <div className="text-center">
                <div className="text-sm text-muted-foreground">Price Change</div>
                <div
                  className={`text-lg font-medium ${
                    adjustedPrice > customBasePrice
                      ? "text-green-600"
                      : adjustedPrice < customBasePrice
                        ? "text-red-600"
                        : "text-muted-foreground"
                  }`}
                >
                  {adjustedPrice === customBasePrice
                    ? "No change"
                    : `${adjustedPrice > customBasePrice ? "+" : ""}₹${(adjustedPrice - customBasePrice).toLocaleString()}`}
                </div>
              </div>
            </div>

            {/* Price Adjustments Section */}
            <div className="grid grid-cols-5 gap-4 p-4 bg-blue-50 rounded-lg border">
              <div className="text-center">
                <Label className="text-sm font-medium">Condition Pricing</Label>
              </div>
              {(["Excellent", "Very Good", "Good", "Average", "Poor"] as VehicleCondition[]).map((condition) => (
                <div key={condition} className="space-y-2">
                  <Label className="text-xs text-center block">{condition}</Label>
                  <div className="flex items-center space-x-1">
                    <span className="text-xs">₹</span>
                    <Input
                      type="number"
                      value={conditionPriceAdjustments[condition]}
                      onChange={(e) =>
                        setConditionPriceAdjustments((prev) => ({
                          ...prev,
                          [condition]: Number(e.target.value),
                        }))
                      }
                      className="h-8 text-xs"
                      placeholder="0"
                    />
                  </div>
                  <div className="text-xs text-center text-muted-foreground">
                    = ₹{calculateAdjustedPrice(customBasePrice, condition).toLocaleString()}
                  </div>
                </div>
              ))}
            </div>

            {/* 300-Point Questions */}
            <div className="space-y-4">
              <h3 className="text-lg font-semibold flex items-center gap-2">
                <Calculator className="h-5 w-5" />
                Complete 300-Point Inspection Questions
              </h3>

              {(() => {
                const questions = inspectionQuestions[inspectingProduct.type as keyof typeof inspectionQuestions]
                if (!questions) {
                  return (
                    <div className="text-center py-8 text-muted-foreground">
                      No inspection questions available for {inspectingProduct.type}
                    </div>
                  )
                }

                return (
                  <Accordion type="multiple" className="w-full">
                    {Object.entries(questions).map(([category, categoryQuestions]) => {
                      const answeredCount = categoryQuestions.filter((_, index) => {
                        const questionId = `${inspectingProduct.type}_${Object.values(questions).flat().indexOf(categoryQuestions[index]) + 1}`
                        return inspectionAnswers[questionId]
                      }).length

                      const categoryScore = categoryQuestions.reduce((sum, _, index) => {
                        const questionId = `${inspectingProduct.type}_${Object.values(questions).flat().indexOf(categoryQuestions[index]) + 1}`
                        const condition = inspectionAnswers[questionId] || "Good"
                        return sum + Math.round(1 * conditionPoints[condition])
                      }, 0)

                      const maxCategoryScore = categoryQuestions.length

                      return (
                        <AccordionItem key={category} value={category}>
                          <AccordionTrigger className="text-left">
                            <div className="flex items-center justify-between w-full mr-4">
                              <span className="font-medium">{category}</span>
                              <div className="flex items-center gap-4">
                                <Badge variant="outline">
                                  {answeredCount}/{categoryQuestions.length} answered
                                </Badge>
                                <Badge variant="secondary">
                                  {categoryScore}/{maxCategoryScore} points
                                </Badge>
                              </div>
                            </div>
                          </AccordionTrigger>
                          <AccordionContent>
                            <div className="grid gap-4">
                              {categoryQuestions.map((question, index) => {
                                const questionId = `${inspectingProduct.type}_${Object.values(questions).flat().indexOf(question) + 1}`

                                return (
                                  <Card key={questionId} className="p-4">
                                    <div className="space-y-3">
                                      <div className="flex items-start justify-between">
                                        <div className="flex-1">
                                          <div className="flex items-center gap-2 mb-2">
                                            <Badge variant="secondary" className="text-xs">
                                              {index + 1}
                                            </Badge>
                                            <span className="text-xs text-muted-foreground">1 point</span>
                                          </div>
                                          <p className="font-medium">{question}</p>
                                        </div>
                                      </div>

                                      <RadioGroup
                                        value={inspectionAnswers[questionId] || ""}
                                        onValueChange={(value) =>
                                          handleAnswerChange(questionId, value as VehicleCondition)
                                        }
                                      >
                                        <div className="grid grid-cols-5 gap-2">
                                          {(
                                            ["Excellent", "Very Good", "Good", "Average", "Poor"] as VehicleCondition[]
                                          ).map((conditionOption) => (
                                            <div key={conditionOption} className="flex items-center space-x-2">
                                              <RadioGroupItem
                                                value={conditionOption}
                                                id={`${questionId}-${conditionOption}`}
                                              />
                                              <Label
                                                htmlFor={`${questionId}-${conditionOption}`}
                                                className="text-xs cursor-pointer"
                                              >
                                                {conditionOption}
                                              </Label>
                                              <div className="text-xs text-muted-foreground">
                                                (₹
                                                {calculateAdjustedPrice(
                                                  customBasePrice,
                                                  conditionOption,
                                                ).toLocaleString()}
                                                )
                                              </div>
                                            </div>
                                          ))}
                                        </div>
                                      </RadioGroup>

                                      {inspectionAnswers[questionId] && (
                                        <div className="flex items-center justify-between text-sm">
                                          <Badge
                                            className={conditionColors[inspectionAnswers[questionId]]}
                                            variant="secondary"
                                          >
                                            {inspectionAnswers[questionId]}
                                          </Badge>
                                          <span className="text-muted-foreground">
                                            Points: {Math.round(1 * conditionPoints[inspectionAnswers[questionId]])} / 1
                                          </span>
                                        </div>
                                      )}
                                    </div>
                                  </Card>
                                )
                              })}
                            </div>
                          </AccordionContent>
                        </AccordionItem>
                      )
                    })}
                  </Accordion>
                )
              })()}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  )
}


